---
- hosts: all
  connection: local
  become: true

  tasks:
  - name: install htop
    apt:
      name: htop        
  - name: install git
    apt:
      name: git
      state: present
  - name: install tree
    apt: 
      name: tree
      state: present
